cache:
  directories:
    - $HOME/.gradle/wrapper/
sudo: required
services:
  - docker
dist: trusty
language: java
jdk:
  - oraclejdk8
deploy:
  provider: script
  script: scripts/install.sh
  on:
    branch: master
