cache:
  directories:
    - $HOME/.gradle/wrapper/
sudo: required
services:
  - docker
dist: trusty
language: java
jdk:
  - oraclejdk8
env:
  - ORG_GRADLE_PROJECT_organization="Waranga News Inc." ORG_GRADLE_PROJECT_projectName="Waranga News" ORG_GRADLE_PROJECT_projectId=wnews ORG_GRADLE_PROJECT_projectUrl="http://wnews.org.au" gaTrackingId="" disqusShortName=""


deploy:
  provider: script
  script: scripts/install.sh
  on:
    branch: master
