wnews:
  build: .
  links:
    - sling
  command: build deployBundle startBundle
  volumes_from:
    - wnews-gradle-cache
whistlepost:
  image: micronode/whistlepost
  links:
    - sling
  command: build deployBundle startBundle
  volumes_from:
    - whistlepost-gradle-cache
sling:
  image: apachesling/sling
  mem_limit: 512m
  #ports:
  #  - 8081:8080
  environment:
    - "JAVA_OPTS=-Dosgi.http.endpoint=http://0.0.0.0:8080/"
  volumes:
    - "./sling.properties:/opt/sling/sling.properties"
  volumes_from:
    - sling-data
sling-data:
  image: tianon/true
  volumes:
    - /opt/sling/sling
haproxy:
  image: tutum/haproxy
  links:
    - sling
  ports:
    - "80:80"
    - "1936:1936"
  mem_limit: 134217728
wnews-gradle-cache:
  image: cogniteev/echo:latest
  volumes:
    - /root/.gradle
whistlepost-gradle-cache:
  image: cogniteev/echo:latest
  volumes:
    - /root/.gradle
