---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/advertisements
  label: Advertisments
  create: all
  match: "**/list/*"
  new_doc_ext: json
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/list/*"
  new_doc_ext: json
upload_dir: wnews
public_path: https://s3-ap-southeast-2.amazonaws.com/wp-media-lib/wnews
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: build/libs
  install_dependencies_command: npm install
  preview_docker_image: micronode/whistlepost
  mount_path: "/opt/sling/bundles/install/50"
  working_dir: "/opt/sling"
  instant_preview_command: "./gradlew build"
