---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
  new_doc_ext: json
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build/libs
  preview_docker_image: micronode/whistlepost
  mount_path: "/opt/sling/bundles/install/50"
  working_dir: "/opt/sling"
  instant_preview_command: "./gradlew build"
