---
label: Recipe
hide_body: true
fields:
- type: text
  name: sling:resourceType
  label: sling:resourceType
- type: datetime
  name: date
  label: date
- type: text
  name: title
  label: title
- type: file
  name: media
  label: media
- type: textarea
  name: abstract
  label: abstract
- type: field_group
  name: body
  label: body
  fields:
  - type: list
    name: pars
    label: pars
- type: list
  name: ingredients
  label: ingredients
- type: list
  name: method
  label: method
- type: text
  name: testimonials
  label: testimonials
- type: boolean
  name: published
  label: published
- type: text
  name: sidebar
  label: sidebar
